name: Project

on:
  push:
    branches: [master, backend-dev, test-fronted]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '9.0'
      
      - name: Restore
        run: dotnet restore ./backend
        
      - name: Build
        run: dotnet build ./backend --configuration Release --no-restore
          
      - name: Tests
        run: dotnet test ./backend/Backend.Tests --configuration Release --no-build --verbosity normal
        
      - name: Publish
        run: dotnet publish ./backend --configuration Release --no-build
  build-frontend:
    