name: Project

on:
  push:
    branches: [master, backend-dev, test-fronted]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '9.0'
      
      - name: Restore
        run: dotnet restore ./backend
        
      - name: Build
        run: dotnet build ./backend --configuration Release --no-restore
          
      - name: Tests
        run: dotnet test ./backend/Backend.Tests --configuration Release --no-build --verbosity normal
        
      - name: Publish
        run: dotnet publish ./backend --configuration Release --no-build
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node
        uses: actions/setup-node@v3
        with: 
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Build Next
        run: |
          cd frontend
          npm run build

  docker-compose:
    runs-on: ubuntu-latest
    needs: [ build-backend, build-frontend ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate compose.yaml
        run: docker-compose config

      - name: Build and run containers
        run: docker-compose up --build -d

      - name: Check running containers
        run: docker-compose ps